### ISSUE TITLE
name and addresses missing from ez part 0

### ISSUE THREAD

**Issue by fgregg** [jsfenfen/990-xml-database#25]
hi @jsfenfen, 

I think I'm just missing something obvious, but the [`return_ez_part_0` model](https://github.com/jsfenfen/990-xml-database/blob/master/irsdb/return/models.py#L1995), does not seem to have the name and address of the org.

Where can I get that info?

**Comment by jsfenfen** [comment]
Heyo @fgregg that material is available in the [return header section](http://www.irsx.info/metadata/parts/returnheader990x_part_i.html). It's useful because it's identically structured for all forms (e.g. 990/990PF/990EZ) but annoyingly there's no documentation. 

You can sorta puzzle stuff out by reading the xpath components; I believe name is [here](http://www.irsx.info/metadata/variable/returnheader990x_part_i-BsnssNm_BsnssNmLn1Txt.html) and address starts with [this](http://www.irsx.info/metadata/variable/returnheader990x_part_i-USAddrss_AddrssLn1Txt.html).
